permissions:
  contents: write

name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"  # every day at midnight IST
    
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Bhoomi-112
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=purple&color_snake=#c084fc
      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
