name: Generate Snake

on:
  schedule:
    - cron: "0 18 * * *" # Midnight IST (18:00 UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#8e44ad&color_dots=#000000,#8e44ad,#9b59b6,#af7ac5,#d2b4de

